alias l='clear; ls -l'
alias ll='clear; ls -la'
alias testify='./bin/test --include-branch-commits'
alias logify='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias stylify='./bin/style --include-branch-commits'
alias styleify='./bin/style --include-branch-commits'
alias tserve='tmux attach -t server'
alias graphqldump='bin/rails graphql:schema:dump'
alias dumpgraphql='bin/rails graphql:schema:dump'
